### ISSUE TITLE
(Master) - hangs on Loading BTC rate & Loading pool stats

### ISSUE THREAD

**Issue by cmbconcretefire** [nemosminer/NemosMiner-v2.4.1#252]
I adjusted startahashpool.bat to my liking and fired up the miner. It benchmarked X17 and when it was time to benchmark another algo, the yellow writing came up > Loading BTC rate from Coinbase and under that > Loading Pool Stats.....

I gave it about 20 minutes to change but it never did. It just kept on mining X17. I shut the miner down and restarted it. NOW it won't even go past "Loading BTC rate and Loading pool stats." 

Why?

**Comment by nemosminer** [comment]
latest release or master?

**Comment by Remie9** [comment]
Same issue here. The interface also hangs and it get stuck in Loading pool stats. Let me know what details are needed. log file? This what I have on the log. I think it is where it got stuck:

--------------------------------------------------------------------------------
Sleeping 30
Starting Cycle
Loading BTC rate from 'api.coinbase.com'..
Loading pool stats..
PS>TerminatingError(Invoke-WebRequest): "The remote server returned an error: (503) Server Unavailable."
**********************
Windows PowerShell transcript start
Start time: 20180501105556
Username: DESKTOP-CQXXX\Jeremie
RunAs User: DESKTOP-CQXXX\Jeremie
Configuration Name: 
Machine: DESKTOP-CQFJVI6 (Microsoft Windows NT 10.0.16299.0)
Host Application: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -version 5.0 -executionpolicy bypass -windowstyle normal -command .\NemosMiner-v3.1.ps1 -ConfigFile '.\Config\config.json'
Process ID: 13756
PSVersion: 5.1.16299.251
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.16299.251
BuildVersion: 10.0.16299.251
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Finding available TCP Port
PS>TerminatingError(New-Object): "Exception calling ".ctor" with "2" argument(s): "No connection could be made because the target machine actively refused it 127.0.0.1:4068""
Miners API Port: 4068
Starting Brains for Plus...
Starting Earnings Tracker...
Starting Cycle
Loading BTC rate from 'api.coinbase.com'..
Loading pool stats..
Computing pool stats..
Loading miners..
Comparing miners and pools..
Starting miner
      1BTC = 8970.62 USD
+++++ "my BTC address"
  ahashpool Balance= 0.00107196 13%
Trust Level                      0%
 Avg based on [ 00 days 00:01 ]
Average BTC/H                    BTC = 0.00000000 | mBTC = 0.000
Average BTC/D
                    BTC = 0.00000000 | mBTC = 0.000
Estimated Pay Date               Unknown > 0.008 BTC
+++++
